name: Dependabot AutoMerge
on:
  pull_request_target:
    branches: [master]

jobs:
  publish:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: Install Node v17
        uses: actions/setup-node@v2
        with:
          node-version: "17.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript compiler
        run: npm run type-check

      - name: Merge PR
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.pulls.merge({
              merge_method: "squash",
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{github.token}}
